### ISSUE TITLE
._. interfere's with Google Analytics

### ISSUE THREAD

**Issue by boostermedia** [unnoon/bottom_line#1]
If you send a Google Analytics call to the old gaq library, it interferes with their character escaping. They have a character escape object that checks if each character of your GA value is in the object. If you have an underscore in your string, this will replace the underscore with an attempt to inject the entire bottom_line object into the analytics.

**Comment by unnoon** [comment]
the bottom_line object is not defined on the object itself but on the prototype attached to an object and is not enumerable. So character escaping on object properties should not be an issue. Unless ga attaches logic on the existence of an underscore property without using a hasOwnProperty check there should be no issues. If this is the case I would say the bug is not in bottom_line but in ga. My feeling is however that something else is going wrong. However since I'm on sabbatical and not running ga at the moment, could you guys give some more info or a link maybe where I can test this?

**Comment by boostermedia** [comment]
Unfortunately, it definitely is an issue with the Google Analytics old library, but at the same time, it's doing something i could imagine a lot of people doing...
It creates a map of replacement characters like:

`map = { '-': '1', '+':'2', '*':'3' };`

Then it checks each character of a string against this like:

`myString[i] = map[myString[i]]`

So you can see if there's an `_` in this map, it's going to replace it with an object...
I agree they should be checking, but this does seem like potentially common behavior.

**Comment by unnoon** [comment]
ouch... I see now. Well there is no way for me to fix this. The solution would be not sending property names that include underscores to ga then ;-) So that's pretty much a death stab to this syntax... I guess I'll go full functional then. In the meantime I can soften it a bit in cases where in evaluation toString is called on the bottom_line object and return an empty string in those cases (renaming toString to stringify for other cases). However this will almost certainly not fix the ga case. I'll implement this in the next bottom_line version though, let me know if it is fixed then.

**Comment by boostermedia** [comment]
yeah, our work around for now is exactly what you suggest :P
We do some string replaces and make sure that no _'s are sent to GA. This is not idea, but it works around the issue at least.

**Comment by unnoon** [comment]
Okay I've released a new version. I've renamed toString to stringify and made toString return an empty string when it is called on the bottom_line object. This should semi fix cases where toString is called implicitly in evaluation. Let me know if this (by chance) fixes the ga issue!? (also fixed an issue with getters and setters as a bonus :-)

**Comment by boostermedia** [comment]
Awesome!
Sadly the new version removed some stuff that breaks things for us. We'll keep using our work around for now and fix things for our updated game template. Thanks!!

**Comment by unnoon** [comment]
Aaai that's to bad. If it is the mixin stuff there is a fix for it in the slotmachine bl006 branch. Note that you can inject your own methods using the _.inject function. So in this branch I custom add the mixin function. In any case if you have a feature request let me know!
